on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

name: Continuous integration

jobs:
  fmt:
    name: Rustfmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v18
      - uses: HatsuneMiku3939/direnv-action@v1
      - uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check

  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v18
      - uses: HatsuneMiku3939/direnv-action@v1
      - uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --all-features --workspace --examples -- -D warnings

  test-nix:
    name: Test Nix
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v18
      - uses: HatsuneMiku3939/direnv-action@v1
      - uses: actions-rs/cargo@v1
        with:
          command: test
          args: --all-features --workspace --examples

  test-stable:
    name: Test Stable
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - uses: actions-rs/cargo@v1
        with:
          command: test
          args: --all-features --workspace --examples